{
  "num_messages": 300,
  "ticker_interval": "5s",
  "topic": "load-test",
  "key": "load-key",
  "enable_metrics": true,
  "brokers": ["localhost:9092", "localhost:9093"],
  "num_consumers": 3,
  "num_producers":3,
  "consumer_group": "loadgen-group",
  "partitions": 6,
  "replication": 2,
  "payload_format": "json",
  "min_payload_size": 512,
  "max_payload_size": 1048576,
  "message_rate": 100,
  enable_webhook: true,
  "webhook_endpoint": "http://localhost:8082/webhook"
}
